name: flutter_pay
description: Flutter plugin that help you make payments through Apple and Google Pay
version: 1.0.1
homepage: https://github.com/xamelon/flutter_pay

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xamelon.flutter_pay
        pluginClass: FlutterPayPlugin
      ios:
        pluginClass: FlutterPayPlugin
        
